function table_ct_cl1_cl2_given_d = compute_table_vm(I_peri_l1,I_peri_l2,kappa_fix,kappa_peri,prob_ct,p_match,log_odds_accumulated,nbins_I,bins_I,ang_stim)

dims=[2,nbins_I*ones(1,2)];
log_table_ct_cl1_cl2_given_d = zeros(dims);
elems=cartprod(1:2,1:nbins_I,1:nbins_I);

loglik_ct=log([sigmoid(log_odds_accumulated),1-sigmoid(log_odds_accumulated)]);

for i=1:size(elems,1)
    if elems(i,1)==1
    log_temp =... 
          loglik_ct(1) ...
        + log(circ_vmpdf(I_peri_l1,-ang_stim,kappa_peri)*p_match+circ_vmpdf(I_peri_l1,ang_stim,kappa_peri)*(1-p_match)) ...
        + log(circ_vmpdf(I_peri_l2,-ang_stim,kappa_peri)*p_match+circ_vmpdf(I_peri_l2,ang_stim,kappa_peri)*(1-p_match)) ...
        + log(prob_ct(1)) ...
        + log(circ_vmpdf(bins_I(elems(i,2)),-ang_stim,kappa_fix)*p_match+circ_vmpdf(bins_I(elems(i,2)),ang_stim,kappa_fix)*(1-p_match)) ...
        + log(circ_vmpdf(bins_I(elems(i,3)),-ang_stim,kappa_fix)*p_match+circ_vmpdf(bins_I(elems(i,3)),ang_stim,kappa_fix)*(1-p_match));
    else
        log_temp =... 
          loglik_ct(2) ...
        + log(circ_vmpdf(I_peri_l1,ang_stim,kappa_peri)*p_match+circ_vmpdf(I_peri_l1,-ang_stim,kappa_peri)*(1-p_match)) ...
        + log(circ_vmpdf(I_peri_l2,ang_stim,kappa_peri)*p_match+circ_vmpdf(I_peri_l2,-ang_stim,kappa_peri)*(1-p_match)) ...
        + log(prob_ct(2)) ...
        + log(circ_vmpdf(bins_I(elems(i,2)),ang_stim,kappa_fix)*p_match+circ_vmpdf(bins_I(elems(i,2)),-ang_stim,kappa_fix)*(1-p_match)) ...
        + log(circ_vmpdf(bins_I(elems(i,3)),ang_stim,kappa_fix)*p_match+circ_vmpdf(bins_I(elems(i,3)),-ang_stim,kappa_fix)*(1-p_match));
    end
    log_table_ct_cl1_cl2_given_d(...
       elems(i,1),...
       elems(i,2),...
       elems(i,3)) = log_temp;
end
table_ct_cl1_cl2_given_d = exp(log_table_ct_cl1_cl2_given_d-logsumexp2(log_table_ct_cl1_cl2_given_d(:)'));
end